version: "3.1"
services:
    www:
        build: .
        ports: 
            - "3000:80"
        volumes:
            - ./src:/var/www/html
        networks:
            - default 
volumes:
    persistent: